#!/bin/bash
cd "$(dirname "$0")"



template=$(cat templates/Dockerfile.template)
sdl_packages=$(cat templates/Dockerfile.sdl_packages)
effil=$(cat templates/Dockerfile.effil)
luajit_install=$(cat templates/Dockerfile.luajit_install)
lua54_install=$(cat templates/Dockerfile.lua54_install)
luajit_compile=$(cat templates/Dockerfile.luajit_compile)
lua_compile=$(cat templates/Dockerfile.lua_compile)


generate(){
    if [ "$luajit" -eq "1" ]; then
        lua_ver="5.1"
    fi

    out=$template
    out="${out/---LUA-VER---/"$lua_ver"}"


    if [ "$luajit" -eq "1" ]; then
        out="${out/---LUA-INSTALL---/"$luajit_install"}"
    fi

    if [ "$lua_ver" == "5.4" ]; then
        out="${out/---LUA-INSTALL---/"$lua54_install"}"
    fi

    if [ "$lua_ver" == "5.4" ]; then
            out="${out/---EFFIL---/""}" # not supported for lua 5.4 yet
    else
        out="${out/---EFFIL---/"$effil"}"
    fi

    if [ "$full" -ne "1" ]; then
        out="${out/---SDL-PACKAGES---/""}"
    else
        out="${out/---SDL-PACKAGES---/"$sdl_packages"}"
    fi

    if [ "$compile" -eq "1" ]; then
        if [ "$luajit" -eq "1" ]; then
            out="${out/---LUA-COMPILE---/"$luajit_compile"}"
        else
            out="${out/---LUA-COMPILE---/"$lua_compile"}"
        fi
    else
        out="${out/---LUA-COMPILE---/""}"
    fi

    echo "# Generated by generate_dockerfiles.sh" > "$out_file"
    echo "$out" >> "$out_file"
}

compile="1" # compile .lua files for all version

luajit="1"
full="0"
out_file="Dockerfile"
generate

luajit="1"
full="1"
out_file="Dockerfile.full"
generate

luajit="0"
lua_ver="5.4"
full="0"
out_file="Dockerfile.54"
generate

luajit="0"
lua_ver="5.4"
full="1"
out_file="Dockerfile.54-full"
generate


echo done
